name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:

    services:
      mongodb:
        image: mongo:5.0.6
        ports:
          - 27017:27017

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [ 1.28.1 ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: build and test
        run: |
          deno --version --unstable
          deno test --coverage=docs/reports/coverage -A --unstable
        env:
          CI: true
