name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:
    if: ${{startsWith(github.event.head_commit.message, 'WIP') != true}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [ 1.39.0 ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: build and test
        run: |
          deno --version --unstable
          deno task test
          deno task coverage
        env:
          CI: true
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info

